version: '{build}'
skip_tags: true
image:
  - Visual Studio 2019 Preview
  - Ubuntu
configuration: Release
test: off
build_script:
  - ps: ./Build.ps1
  - ps: ./BuildNativeUWP.ps1
for:
-
  matrix:
    only:
      - image: Ubuntu
  build_script:
  - sh build.sh
artifacts:
- path: artifacts/Serilog.*.nupkg
- path: artifacts/Serilog.*.snupkg
deploy:
- provider: NuGet
  api_key:
    secure: hHbvIML/EUrC0+eQvNS0oTd0++/EJHLGUrfvcvY1LBPY4FKRgAOkkq5sWygTNHY7
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: p4LpVhBKxGS5WqucHxFQ5c7C8cP74kbNB0Z8k9Oxx/PMaDQ1+ibmoexNqVU5ZlmX
  artifacts:
    /Serilog.*\.nupkg/
    /Serilog.*\.snupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
